// auth
export const GET_TOKEN = 'GET_TOKEN';
export const VERIFY_TOKEN = 'VERIFY_TOKEN';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

// start from here
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_USER_INFO = 'GET_USER_INFO';
export const REFRESH_TOKEN_BY_REFRESH_TOKEN = 'REFRESH_TOKEN_BY_REFRESH_TOKEN';
export const SET_RELATED_COURSE_DATA = 'SET_RELATED_COURSE_DATA';

// subject
export const GET_SIMPLE_SUBJECT = 'GET_SIMPLE_SUBJECT';

// account
export const SET_VIEWING_ACCOUNT = 'SET_VIEWING_ACCOUNT';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const HAS_EDIT_BUTTON_ACCOUNT = 'HAS_EDIT_BUTTON_ACCOUNT';
export const UPDATE_NEW_USER = 'UPDATE_NEW_USER';
export const UPDATE_USER_TAB = 'UPDATE_USER_TAB';
export const SET_TYPE_VIEW_SEMINAR_USER = 'SET_TYPE_VIEW_SEMINAR_USER';

// company
export const IS_EDITTING_COMPANY = 'IS_EDITTING_COMPANY';
export const SET_VIEWING_COMPANY = 'SET_VIEWING_COMPANY';
export const HAS_EDIT_BUTTON_COMPANY = 'HAS_EDIT_BUTTON_COMPANY';
export const IS_STUDENT_ACCOUNT_TAB = 'IS_STUDENT_ACCOUNT_TAB';
export const SET_COMPANIES_ACCOUNTMGT = 'SET_COMPANIES_ACCOUNTMGT';
export const SET_TAB_COMPANY = 'SET_TAB_COMPANY';
export const SET_COMPANY_SORT_TYPE = 'SET_COMPANY_SORT_TYPE';

//library
export const ADD_LIBRARY = 'ADD_LIBRARY';
export const GET_LIBRARY = 'GET_LIBRARY';
export const SET_OPENED_LIBRARY = 'SET_OPENED_LIBRARY';
export const VIEWING_LIBRARY = 'VIEWING_LIBRARY';
export const SET_FILES = 'SET_FILES';
export const VIEWING_MATERIAL = 'VIEWING_MATERIAL';
export const ADD_FOLDER = 'ADD_FOLDER';

//message
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const GET_MESSAGE = 'GET_MESSAGE';

//profile
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const IS_EDITTING_USER = 'IS_EDITTING_USER';

//reminder
export const GET_REMINDER = 'GET_REMINDER';
export const GET_REMINDER_COUNT = 'GET_REMINDER_COUNT'
export const DISMISS_REMINDER = 'DISMISS_REMINDER';
export const DISMISS_ALL_REMINDER = 'DISMISS_ALL_REMINDER';

//seatingPlan
// Add room seating plan for given dimensions.
export const ADD_SEATING_PLAN = 'ADD_SEATING_PLAN';
export const ISEDIT_SEATING_PLAN = 'ISEDIT_SEATING_PLAN';
export const VIEWING_SEATING_PLAN_TYPE = 'VIEWING_SEATING_PLAN_TYPE';
export const PLAN_TYPE_SELECTED = 'PLAN_TYPE_SELECTED';
export const EDIT_ENABLE = 'EDIT_ENABLE';
export const SET_PLAN = 'SET_PLAN';
export const SET_EDIT_PLAN_TYPE = 'SET_EDIT_PLAN_TYPE';
export const SET_EDIT = 'SET_EDIT';

//seatMap
export const UPDATE_NAME = 'UPDATE_NAME';
export const UPDATE_COLOR = 'UPDATE_COLOR';
export const UPDATE_EMPTY = 'UPDATE_EMPTY';
export const RESET_SEATS = 'RESET_SEATS';
export const SET_SEATS = 'SET_SEATS';

//seminar
export const LOAD_SEMINAR = 'LOAD_SEMINAR';
export const SET_VIEWING_SEMINAR = 'SET_VIEWING_SEMINAR';
export const SET_EDIT_ONSITE_TIME = 'SET_EDIT_ONSITE_TIME';
export const ADD_SEMINAR = 'ADD_SEMINAR';
export const GET_SEMINAR = 'GET_SEMINAR';
export const CHANGE_TAB = 'CHANGE_TAB';
export const UPDATE_CLASS_MATERIAL = 'UPDATE_CLASS_MATERIAL';
export const UPDATE_LIBRARY_DOCUMENTS = 'UPDATE_LIBRARY_DOCUMENTS';
export const IS_EDITTING_SEMINAR = 'IS_EDITTING_SEMINAR';
export const CONFIRM_EDIT_SEMINAR = 'CONFIRM_EDIT_SEMINAR';
export const UPDATE_SEMINAR_EDITABLE = 'UPDATE_SEMINAR_EDITABLE';

//studentContainer
export const GET_STUDENT_CONTAINER = 'GET_STUDENT_CONTAINER';
export const UPDATE_SEAT_NO = 'UPDATE_SEAT_NO';
export const UPDATE_DRAGGABLE = 'UPDATE_DRAGGABLE';
export const UPDATE_COMPANY_COLOR = 'UPDATE_COMPANY_COLOR';
export const RESET_STUDENT_CONTAINER = 'RESET_STUDENT_CONTAINER';
export const SET_STUDENT_CONTAINER = 'SET_STUDENT_CONTAINER';

//student
export const ADD_STUDENT = 'ADD_STUDENT';
export const GET_STUDENT = 'GET_STUDENT';
export const UPDATE_STUDENT_STATUS = 'UPDATE_STUDENT_STATUS';
export const UPDATE_CURRENT_STUDENT = 'UPDATE_CURRENT_STUDENT';
export const UPDATE_EDITABLE = 'UPDATE_EDITABLE';
export const IS_EDITTING_STUDENT = 'IS_EDITTING_STUDENT';
export const VIEWING_CURRENT_STUDENT = 'VIEWING_CURRENT_STUDENT';
export const GET_LIST_STUDENT_COMPANY = 'GET_LIST_STUDENT_COMPANY';

//viewContent
export const UPDATE_CURRENT_SEMINAR = 'UPDATE_CURRENT_SEMINAR';
export const UPDATE_CURRENT_LIBRARY = 'UPDATE_CURRENT_LIBRARY';
export const UPDATE_CURRENT_EVENT = 'UPDATE_CURRENT_EVENT';
export const UPDATE_LIBRARY_CHECK = 'UPDATE_LIBRARY_CHECK';
export const UPDATE_DOCUMENT_CHECK = 'UPDATE_DOCUMENT_CHECK';
export const UPDATE_TEACHER_TAB = 'UPDATE_TEACHER_TAB';

//event
export const SET_NOTE_TITLE = 'SET_NOTE_TITLE';
export const GET_EVENT = 'GET_EVENT';
export const ADD_EVENT = 'ADD_EVENT';
export const SET_VIEWING_EVENT = 'SET_VIEWING_EVENT';
export const VIEWING_NOTE = 'VIEWING_NOTE';

export const EDIT_STATE = {
    NEW: "new",
    EDIT: "edit",
    EDITING: "editing",
};
// export {
//     // auth
//     GET_TOKEN, VERIFY_TOKEN, LOGIN_SUCCESS, LOGIN_FAILURE, LOGOUT, SET_RELATED_COURSE_DATA, GET_USER_INFO, REFRESH_TOKEN_BY_REFRESH_TOKEN,
//     // GET_CONFERENCE_ID,

//     // subject
//     GET_SIMPLE_SUBJECT,

//     // account
//     SET_VIEWING_ACCOUNT, SET_ACCOUNTS, HAS_EDIT_BUTTON_ACCOUNT,
//     UPDATE_NEW_USER, UPDATE_USER_TAB, SET_TYPE_VIEW_SEMINAR_USER,

//     // company
//     IS_EDITTING_COMPANY, SET_VIEWING_COMPANY, HAS_EDIT_BUTTON_COMPANY,
//     IS_STUDENT_ACCOUNT_TAB, SET_COMPANIES_ACCOUNTMGT, SET_TAB_COMPANY,
//     SET_COMPANY_SORT_TYPE,

//     //library
//     ADD_LIBRARY, GET_LIBRARY, SET_OPENED_LIBRARY, VIEWING_LIBRARY, SET_FILES,
//     VIEWING_MATERIAL, ADD_FOLDER,

//     //message
//     ADD_MESSAGE, GET_MESSAGE,

//     //profile
//     SET_USER_PROFILE, IS_EDITTING_USER,

//     //reminder
//     GET_REMINDER, GET_REMINDER_COUNT, DISMISS_REMINDER, DISMISS_ALL_REMINDER,

//     //seatingPlan
//     ADD_SEATING_PLAN, ISEDIT_SEATING_PLAN, VIEWING_SEATING_PLAN_TYPE, PLAN_TYPE_SELECTED,
//     EDIT_ENABLE, SET_PLAN, SET_EDIT_PLAN_TYPE, SET_EDIT,

//     //seatMap
//     UPDATE_NAME, UPDATE_COLOR, UPDATE_EMPTY, RESET_SEATS, SET_SEATS,

//     //seminar
//     LOAD_SEMINAR, SET_VIEWING_SEMINAR, SET_EDIT_ONSITE_TIME, ADD_SEMINAR, GET_SEMINAR,
//     CHANGE_TAB, UPDATE_CLASS_MATERIAL, UPDATE_LIBRARY_DOCUMENTS, IS_EDITTING_SEMINAR,
//     CONFIRM_EDIT_SEMINAR, UPDATE_SEMINAR_EDITABLE,

//     //studentContainer
//     GET_STUDENT_CONTAINER, UPDATE_SEAT_NO, UPDATE_DRAGGABLE, UPDATE_COMPANY_COLOR,
//     RESET_STUDENT_CONTAINER, SET_STUDENT_CONTAINER,

//     //student
//     ADD_STUDENT, GET_STUDENT, UPDATE_STUDENT_STATUS, UPDATE_CURRENT_STUDENT, UPDATE_EDITABLE,
//     IS_EDITTING_STUDENT, VIEWING_CURRENT_STUDENT, GET_LIST_STUDENT_COMPANY,

//     //viewContent
//     UPDATE_CURRENT_SEMINAR, UPDATE_CURRENT_LIBRARY, UPDATE_CURRENT_EVENT, UPDATE_LIBRARY_CHECK,
//     UPDATE_DOCUMENT_CHECK, UPDATE_TEACHER_TAB,

//     //event
//     SET_NOTE_TITLE, GET_EVENT, ADD_EVENT, SET_VIEWING_EVENT, VIEWING_NOTE,

//     //unknown
//     EDIT_STATE,
// };
